### ISSUE TITLE
If i use the uploader many time

### ISSUE THREAD

**Issue by ahmedsliman** [fojuth/plupload#11]
If i want to use the uploader many time in one page so in init for example i have:

@plupload('contents/upload', 'browse', 'uploader-1')

@plupload('contents/upload', 'browse', 'uploader-2')

How can i check which upload is this in the view javascript template "contents/view"

**Comment by fojuth** [comment]
I'm not actually sure what's the question, sorry.

But if you ask how to determine which uploader was used then I guess you could use different views which use different gates (check `$handler_gate` in `plupload/source/views/uploader_base.blade.php`). Since you can use separate gates you can handle each upload differently.

Does this answer your question?
